
# List of course acronyms
course_acronyms = [
    "AAAS", "AAPS", "AASP", "AAST", "ABRM", "AGNR", "AGST",
    "AMSC", "AMST", "ANSC", "ANTH", "AOSC", "ARAB", "ARCH",
    "AREC", "ARHX", "ARHU", "ARMY", "ARSC", "ARTH", "ARTT", "ARTX", "ARUX", "ASTR", "BCHM",
    "BIOE", "BIOI", "BIOL", "BIOM", "BIPH", "BISI", "BMGT",
    "BMSO", "BSCI", "BSCV", "BSGC", "BSOS", "BSST", "BUAC", "BUDT", "BUFN", "BULM", "BUMK",
    "BUSI", "BUSM", "BUSO", "CBMG", "CCJS", "CHBE", "CHEM", "CHIN", "CHPH",
    "CHSE", "CINE", "CINX", "CLAS", "CLAX", "CLFS", "CMLT", "CMLX", "CMSC", "CMNS", "COMM",
    "COMX", "CPBE", "CPCV", "CPDJ", "CPET", "CPGH", "CPJT", "CPMS", "CPPL",
    "CPSA", "CPSD", "CPSF", "CPSG", "CPSN", "CPSP", "CPSS", "DANC", "DATA",
    "EALL", "ECON", "EDCI", "EDCP", "EDHD", "EDHI", "EDMS", "EDPS", "EDSP",
    "EDUC", "EMBA", "ENAE", "ENBC", "ENCE", "ENCO", "ENEB", "ENEE",
    "ENES", "ENFP", "ENGL", "ENGX", "ENMA", "ENME", "ENMT", "ENNU", "ENPM", "ENRE", "ENSE",
    "ENSP", "ENST", "ENTM", "ENTS", "EPIB", "FIRE", "FGSM", "FMSC",
    "FREN", "GBHL", "GEMS", "GEOG", "GEOL", "GERM", "GERS", "GREK", "GVPT",
    "HACS", "HBUS", "HDCC", "HEBR", "HEIP", "HESI", "HESP", "HGLO", "HHUM",
    "HISP", "HIST", "HISX", "HLSA", "HLSC", "HLTH", "HNUH", "HONR", "IDEA",
    "IMDM", "IMMR", "INAG", "INFM", "INST", "ISRL", "ITAL", "ITAX", "IVSP",
    "JAPN", "JOUR", "JWST", "KNES", "KORA", "LACS", "LARC", "LASX", "LATN",
    "LBSC", "LEAD", "LGBT", "LGBX", "LING", "MATH", "MEES",
    "MIEH", "MITH", "MLAW", "MLSC", "MOCB", "MSML", "MSQC", "MUED",
    "MUET", "MUSC", "MUSP", "NACS", "NAVY", "NEUR", "NFSC", "NIAS", "PEER", "PERS",
    "PHIL", "PHIX", "PHPE", "PHPX", "PHSC", "PHYS", "PLCY", "PLSC", "PORT", "PSYC", "RDEV",
    "RELS", "RELX", "RUSS", "SLAA", "SLLC", "SLLX", "SMLP", "SOCY", "SPAN", "SPAX", "SPHL",
    "STAT", "SURV", "TDPS", "THET", "THEX", "TLPL", "TLTC", "UMEI",
    "UNIV", "URSP", "USLT", "VMSC", "WMSX", "WEID", "WGSS", "XPER"
]

CSV_CATALOG_COURSES_HEADER = [
    "COURSE PREFIX",
    "COURSE NUMBER",
    "NAME",
    "CREDITS",
    "DESCRIPTION",
    "PREREQUISITE",
    "RESTRICTION",
    "FORMERLY NAMED",
    "RECOMMENDED",
    "CREDIT ONLY GRANTED FOR",
    "REPEATABLE TO",
    "CROSS-LISTED",
    'COREQUISITE'
]

CSV_SOC_HEADER = [
    "COURSE NUMBER",
    "COURSE TITLE",
    "MINIMUM CREDITS",
    "MAXIMUM CREDITS",
    "GRADING METHOD",
    "GEN_EDS FULFILLED",
    "SECTION ID",
    "INSTRUCTOR",
    "TOTAL SEATS",
    "OPEN SEATS",
    "WAITLIST COUNT",
    "LECTURE TIME",
    "2ND LISTED LECTURE TIME",
    "3RD LISTED LECTURE TIME",
    "DISCUSSION TIME",
    "2ND LISTED DISCUSSION TIME",
    "LAB TIME",
    "2ND LISTED LAB TIME",
    "LECTURE ROOM",
    "2ND LISTED LECTURE ROOM",
    "3RD LISTED LECTURE ROOM",
    "DISCUSSION ROOM",
    "2ND LISTED DISCUSSION ROOM",
    "LAB ROOM",
    "2ND LISTED LAB ROOM",
    "UNSPECIFIED TIME MESSAGE",
    "HAS LECTURE",
    "HAS 2ND LISTED LECTURE",
    "HAS 3RD LISTED LECTURE",
    "HAS DISCUSSION",
    "HAS 2ND LISTED DISCUSSION",
    "HAS LAB",
    "HAS 2ND LISTED LAB",
    "IS NORMAL",
    "IS BLENDED (NORMAL AND ONLINE)",
    "IS ONLINE",
    "SPECIAL RESTRICTION",
    "PREREQUISITE",
    "COREQUISITE",
    "RESTRICTION",
    "CREDIT ONLY GRANTED FOR",
    "FORMERLY",
    "RECOMMENDED",
    "CROSS-LISTED WITH",
    "DESCRIPTION",
]


CSV_BUILDINGS_HEADER = [
    "BUILDING CODE",
    "FULL FORM",
]

CSV_GEN_EDS_HEADER = [
    "GENERAL EDUCATION ACRONYM",
    "GENERAL EDUCATION FULL FORM"
]